name: Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout triggering commit
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}
      - name: Create .env.local
        run: |
          cat << 'EOF' > .env.local
          AKAHU_USER_TOKEN=${{ secrets.AKAHU_USER_TOKEN }}
          AKAHU_APP_TOKEN=${{ secrets.AKAHU_APP_TOKEN }}
          EOF
      - name: Rebuild and restart
        run: docker compose -f ./docker-compose.yml up --build -d
