name: Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout triggering commit
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}

      - name: Rebuild and restart
        run: docker compose -f ./docker-compose.yml up --build -d
